[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "ImprovedLoadouts"
description = "Changes loadout icons to currently equipped upgrades. Press 'L' to rename loadout."
websiteUrl = "https://github.com/Little-Sparroh/ImprovedLoadouts"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/ImprovedLoadouts.dll"
target = "BepInEx/plugins/ImprovedLoadouts.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


